version: '3'

volumes:
  cache:
    driver: local

services:
  postgres:
    image: 'postgres:15-alpine'
    container_name: 'todo-app'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=todo'

  app:
    build: ./
    container_name: 'todo-app'
    ports:
      - 8080:8080


  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
